# Generated by Django 5.1.3 on 2024-11-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_task_observations_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
